# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

python:
  - 3.7

os:
  - linux

notifications:
  email: false

install:
  - pip install --quiet black coverage flake8

script:
  - flake8
  - black --check .
  - if [ ! "$TRAVIS_PULL_REQUEST" = "false" ]; then coverage run setup.py test --addopts "-v -m 'not notebook'"; fi
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then pip install -e ".[notebooks]"; coverage run setup.py test; fi

after_success:
  - codecov

branches:
  only:
  - master
