# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

python:
  - 3.7

os:
  - linux

notifications:
  email: false


matrix:
  include:
    - env: EXTRA_TESTS = 0
  allow_failures:
    - env: EXTRA_TESTS = 1
  fast_finish: true


install:
  - pip install --quiet black coverage flake8 codecov

script:
  - flake8
  - black --check .
  - if [ "$EXTRA_TESTS" ];  then pip install -e ".[notebooks]"; coverage run setup.py test; fi
  - if [ ! "$EXTRA_TESTS" ]; then coverage run setup.py test --addopts "-v -m 'not notebook'"; fi

after_success:
  - codecov

branches:
  only:
  - master
